stages:
  - test

variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
    CROSS_REMOTE: 1
    DOCKER_TLS_CERTDIR: ""

services:
    - docker:dind

test:
  stage: test
  image: rust:latest
  script:
    # Install cross
    - cargo install cross --git https://github.com/cross-rs/cross
    # Test compilation
    - cross test --lib --target arm-linux-androideabi
