image: "rust:latest"
stages:
  - build
  - package

build windows:
  stage: build
  script:
    - apt update && apt upgrade -y
    - apt install -y g++-mingw-w64-x86-64
    - rustup target add x86_64-pc-windows-gnu
    - rustup toolchain install stable-x86_64-pc-windows-gnu
    - cargo build --release --target x86_64-pc-windows-gnu
  rules:
    - if: '$CI_COMMIT_REF_NAME == "test-cross-compilation"'
  artifacts:
    name: "Windows x86-64 compile"
    expire_in: 10 min
    paths:
      -  target/x86_64-pc-windows-gnu/release/meerkat.exe

build linux:
  stage: build
  script:
    - apt update && apt upgrade -y
    - rustup target add x86_64-unknown-linux-gnu
    - cargo build --release --target x86_64-unknown-linux-gnu
  rules:
    - if: '$CI_COMMIT_REF_NAME == "test-cross-compilation"'
  artifacts:
    name: "Linux x86-64 compile"
    expire_in: 10 min
    paths:
      - target/x86_64-unknown-linux-gnu/release/meerkat

build_collect:
  stage: build
  needs:
    - build linux
    - build windows
  dependencies:
    - build linux
    - build windows
  script:
    # Create the directory for all executables
    - mkdir -p ./server/release
    # Copy the windows executable inside the server folder
    - cp ./target/x86_64-pc-windows-gnu/release/meerkat.exe ./server/release
    # Copy the linux executable inside the server folder
    - cp ./target/x86_64-unknown-linux-gnu/release/meerkat ./server/release
  artifacts:
    name: "Server executables"
    expire_in: 30 min
    paths:
      - server/
  rules:
    - if: '$CI_COMMIT_REF_NAME == "test-cross-compilation"'

package:
  stage: package
  image: node:latest
  needs: 
    - build_collect
  dependencies:
    - build_collect
  script:
    - npm i
    - npx vsce package
  artifacts:
    paths: 
      - meerkat.vsix
    when: on_success
    expire_in: 10 days
  rules:
    - if: '$CI_COMMIT_REF_NAME == "test-cross-compilation"'
  
