image: "rust:latest"
stages:
  - build

build_windows:
  stage: build
  script:
    - apt update && apt upgrade -y
    - apt install -y g++-mingw-w64-x86-64
    - rustup target add x86_64-pc-windows-gnu
    - rustup toolchain install stable-x86_64-pc-windows-gnu
    - cargo build --target x86_64-pc-windows-gnu
  rules:
    - if: '$CI_COMMIT_REF_NAME == "test-cross-compilation"'
  artifacts:
    name: "Compiled stuff"
    paths:
      - target/

build_linux:
  stage: build
  script:
    - apt update && apt upgrade -y
    - rustup target add x86_64-unknown-linux-gnu
    - cargo build --target x86_64-unknown-linux-gnu
  rules:
    - if: '$CI_COMMIT_REF_NAME == "test-cross-compilation"'
  artifacts:
    name: "Compiled stuff"
    paths:
      - target/
