# This file is a template, and might need editing before it works on your project.
# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/rust/tags/
image: "rust:latest"
stages:
    - build
    - package

before_script:
    - "npm install"

# Use npm to build the project
build:
    stage: build
    script:
        - npm run compile

# Use vscode package tool to package the extenssion
package:
    stage: package
    script:
        - npm install -g vsce
        - vsce package
