stages:
  - test

variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
    CROSS_REMOTE: 1
    DOCKER_TLS_CERTDIR: ""

services:
    - docker:18.09-dind

test:
  stage: test
  image: haelty/rust-test-cross
  only:
    - main
  script:
      - cross test --lib --target arm-linux-androideabi
