# This file is a template, and might need editing before it works on your project.
# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/rust/tags/
image: "rust:latest"
stages:
    - build client
    - compile server
    - package

before_script:
    - "npm install"

# Use npm to build the project
build_client:
    stage: build client
    script:
        - tsc -b

# Use cargo to compile server
compile_server:
    stage: compile server
    script:
        - cargo build --release # because optimized build can be reused in next stage

# Use vscode package tool to package the extenssion
package:
    stage: package
    script:
        - npx vsce package
