name: Deployment

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  compile-server:
    name: Compile-server
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - x86_64-pc-windows-gnu
          - x86_64-unknown-linux-gnu
    steps:
      - uses: actions/checkout@v3
      - name: Installing Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true
      - name: Compiling for ${{ matrix.target }}
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target=${{ matrix.target }}
      - name: Uploading artifacts
        uses: actions/upload-artifact@v3
        with:
          name: server
          path: target/${{ matrix.target }}/release/meerkat*
  compile-client:
    name: Deploy-extenssion
    needs: [compile-server]
    runs-on: ubuntu-latest
    steps: 
      - name: Installing NPM
        run: npm install
      - name: Packaging extenssion
        run: npx vsce package
    #   - name: Deploying extenssion
    #     run: npx vsce publish --pat $DEPLOY_TOKEN --target win32-x64 linux-x64
      - name: Uploading artifacts
        uses: actions/upload-artifact@v3
        with:
          name: extenssion
          path: ./*.vsix 


  