name: Rust

on:
  push:
#     branches: [ "main" ]
  pull_request:
#     branches: [ "main" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  check-rust:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
  check-client:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x, 20.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: npm install
  build-server-windows-x86:
    runs-on: ubuntu-latest
    steps: 
      - name: Update APT
        run: sudo apt update && sudo apt upgrade -y
      - name: Install GCC tools
        run: sudo apt install -y g++-mingw-w64-x86-64
      - name: Add Windows x86_64 to the target
        run: rustup target add x86_64-pc-windows-gnu
      - name: Install toolchain
        run: rustup toolchain install stable-x86_64-pc-windows-gnu
      - name: Compile project
        run: cargo build --release --target x86_64-pc-windows-gnu
  build-server-linux-x86:
    runs-on: ubuntu-latest
    steps: 
      - name: Update APT
        run: sudo apt update && apt upgrade -y
      - name: Add Linux x86_64 to the target
        run: rustup target add x86_64-unknown-linux-gnu
      - name: Compile project
        run: cargo build --release --target x86_64-unknown-linux-gnu
  bundle-server:
    runs-on: ubuntu-latest
    needs: [build-server-linux-x86, build-server-windows-x86]
    steps: 
      - name: Download build artifacts
        uses: actions/download-artifact@v3
      - name: Print directory structure
        run: ls -R
      - name: Create server directory
        run: mkdir -p ./server/release
      - name: Add Linux x86_64 to server directory
        run: cp ./target/x86_64-unknown-linux-gnu/release/meerkat ./server/release
      - name: Add Windows x86_64 to server directory
        run: cp ./target/x86_64-pc-windows-gnu/release/meerkat.exe ./server/release
      - name: Archive server
        uses: actions/upload-artifact@v3
        with:
          name: server
          path: server/
          retention-days: 1
